# -*- coding: utf-8 -*-
"""Gen AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvf_oRBwXWXfh-jvQt5-RMf2Eou1FNiQ
"""

from transformers import pipeline

generator = pipeline(
    model="gpt2"
)
#input prompt
prompt = "Artificial Intelligence in finance will"
#Generate text
result = generator(prompt, max_length=50, num_return_sequences=1)
print("AI Generated text:")
print(result[0]["generated_text"])

