# -*- coding: utf-8 -*-
"""similarity check

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MHYzxVWpPoiBfpgZAHhg_XR3MTZdKhpu
"""

!pip install sentence-transformers

from sentence_transformers import SentenceTransformer, util

# Load model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Input texts
text1 = input("Enter text 1: ")
text2 = input("Enter text 2: ")

# Encode texts
embedding1 = model.encode(text1, convert_to_tensor=True)
embedding2 = model.encode(text2, convert_to_tensor=True)

# Compute cosine similarity
similarity = util.cos_sim(embedding1, embedding2).item()

# Output
print("\nSimilarity score:", round(similarity, 2))

if similarity > 0.75:
    print("Similarity level: High")
elif similarity > 0.45:
    print("Similarity level: Medium")
else:
    print("Similarity level: Low")