# -*- coding: utf-8 -*-
"""time table generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nY_XxRCOEVCADRlJ5uYSZCbvpjwevHg8
"""

import pandas as pd
import random

print("TIMETABLE GENERATOR\n")

# User Inputs
subjects_input = input("Enter subjects (comma separated): ")
days_input = input("Enter days (comma separated): ")
periods_per_day = int(input("Enter number of periods per day: "))

# Process Inputs
subjects = [s.strip() for s in subjects_input.split(",") if s.strip()]
days = [d.strip() for d in days_input.split(",") if d.strip()]

# Validation
if len(subjects) < 1 or len(days) < 1 or periods_per_day <= 0:
    print("Invalid input. Please try again.")
else:
    timetable = {}

    for day in days:
        timetable[day] = random.choices(subjects, k=periods_per_day)

    # Create DataFrame
    df = pd.DataFrame(timetable)
    df.index = [f"Period {i+1}" for i in range(periods_per_day)]

    print("\nTimetable Generated Successfully\n")
    print(df)

    # Save timetable
    df.to_csv("timetable.csv")
    print("\nTimetable saved as timetable.csv")

import pandas as pd
from datetime import datetime

print("MEETING MINUTES GENERATOR\n")

# User Inputs
meeting_title = input("Enter meeting title: ")
date = input("Enter meeting date (DD-MM-YYYY): ")
time = input("Enter meeting time: ")
participants = input("Enter participants (comma separated): ")
agenda = input("Enter agenda points (comma separated): ")
decisions = input("Enter decisions taken (comma separated): ")
action_items = input("Enter action items (comma separated): ")
prepared_by = input("Prepared by: ")

# Process Inputs
participants_list = [p.strip() for p in participants.split(",") if p.strip()]
agenda_list = [a.strip() for a in agenda.split(",") if a.strip()]
decisions_list = [d.strip() for d in decisions.split(",") if d.strip()]
actions_list = [a.strip() for a in action_items.split(",") if a.strip()]

# Create structured meeting minutes
minutes = {
    "Meeting Title": meeting_title,
    "Date": date,
    "Time": time,
    "Participants": ", ".join(participants_list),
    "Agenda": ", ".join(agenda_list),
    "Decisions Taken": ", ".join(decisions_list),
    "Action Items": ", ".join(actions_list),
    "Prepared By": prepared_by,
    "Generated On": datetime.now().strftime("%d-%m-%Y %H:%M:%S")
}

# Convert to DataFrame
df = pd.DataFrame(list(minutes.items()), columns=["Field", "Details"])

print("\n Meeting Minutes Generated Successfully\n")
display(df)

# Save as CSV
df.to_csv("meeting_minutes.csv", index=False)
print("\n File saved as meeting_minutes.csv")

